version: '3.9'
services:
  database:
    build: './database/'
    container_name: 'database-container'
    volumes:
      - ./database/dados:/var/lib/mysql
    ports:
      - 3307:3306

  api:
    build: './'
    container_name: 'api-container'
    volumes:
      - ./:/home/node/api
      - /home/node/api/node_modules
    ports:
      - 4000:4000
    depends_on: 
      - database
    links: 
      - database
